hatch/venv.py

Hello.
I am trying to package Hatch to Fedora and I found one issue.
The problem is that in some Linux distribution where the default Python is still Python 2 you should avoid calling tools like `virtualenv` directly because `virtualenv` without `-3` suffix means Python 2 virtualenv. And because Hatch is Python3-only there is no `virtualenv` command available in build environment during building RPM package.
Moreover when you use `sys.executable` you can be sure that the same Python will be used for virtualenv like it is for running Hatch.
What do you think about it?

Do not call `virtualenv` executable directly

---

tests/commands/test_env.py
tests/commands/test_install.py
tests/commands/test_release.py
tests/commands/test_uninstall.py
tests/commands/test_update.py
tests/test_env_utils.py
tests/utils.py
tox.ini

- skip tests which require an internet connection when it is not available
- install `pytest` into the ok package in `test_package` and run `pytest` as a module inside the package (this make the test depends on internet connection)
With these changes, I am able to run build of RPM for Fedora and also all tests are passing on my local machine.
If you are ok with these changes, please merge it and release a new version so I can build the newest specfile for RPM on it and send it to package review.

Support Fedora packaging

---

.gitignore
AUTHORS.rst
hatch/commands/release.py
tests/commands/test_release.py

This PR attempts to address #33 by making two changes to `hatch release`:
- First and foremost, this adds two flags: `-r/--repository` and `--repository-url`. These are simply passed through to `twine`. If they are not given, the `twine` default behavior will be used. For simplicity, it is an error to use these flags in combination with `-t` (since it is not immediately clear whether `-t` should override `-r` and `--repository-url`, or the other way around).
- Additionally, the behavior of `hatch release` has been changed such that it works correctly with the `TWINE_USERNAME`, `TWINE_REPOSITORY`, and `TWINE_REPOSITORY_URL` environment variables.
The `AUTHORS.rst` file has been updated accordingly.

Support Releases to Alternative Repositories

---

tests/test_utils.py

test_download_file obviously need the internet connection and therefore should be marked with the appropriate decorator.

test_download_file() requires internet connection

---

hatch/create.py

Support for things like
```
"extras": [ "~/.local/share/hatch/CHANGELOG*" ]
```

Support tilde in `extras` globs

---

tests/commands/test_build.py
tests/commands/test_clean.py
tests/commands/test_env.py
tests/commands/test_grow.py
tests/commands/test_init.py
tests/commands/test_install.py
tests/commands/test_new.py
tests/commands/test_release.py
tests/commands/test_test.py
tests/commands/test_uninstall.py
tests/test_env_utils.py

Hello.
I found out that some tests newly require internet and therefore they have to be skipped in an environment without the internet connection.
The latest virtualenv bundles pip 10.0.1. Pip from version 10.0.0 has support for pyproject.toml files (PEP 518) which means that pip now installs build dependencies specified in pyproject.toml file automatically. And it doesn't work without internet obviously.
It would be nice if you can do a release so it would be possible for me to drop downstream patch. Currently, I had to create this patch twice - once for this PR and once for currently released version 0.20.0.
Have a nice day.
Lumír

Add decorator to tests which require internet connection.

---

setup.py

Using `/` is not ambiguous, however `or` is more clear
and is syntax recognised by packaging tools.

setup.py: Use OR to indicate MIT or Apache-2.0

---

hatch/structures.py

Python 3.7 threw an error about bad encoding.

Fixed bad encoding for Python 3.7

---

hatch/files/setup.py

Prevent setup.py from adding a package for `tests`.
This is a fixed version of https://github.com/ofek/hatch/pull/60 , which was abandoned.

Avoid installing tests as a package

---

docs/config/metadata.md

TOML requires that inline tables (`{}`) connect key/value pairs with equal signs (`=`).
Also fix the spelling of content-type. While the Python code uses `content_type` to refer to the attribute, the specification itself needs `content-type`.
This was not caught by the tests, since they specify it Python type-style to the test runner. A suggestion for the future would be to remove the inline test "file" (in e.g. `test_core.py` and `test_utils.py`) and work with real files (or stringified versions thereof).

Inline TOML tables require = between key/value pairs

---

tests/cli/build/test_build.py
tests/cli/env/test_create.py
tests/cli/env/test_prune.py
tests/cli/env/test_remove.py
tests/cli/run/test_run.py

In an offline build environment, all of the following tests fail with something like:
```
E       AssertionError: Creating environment: foo.9000
E         Syncing dependencies
E         
E       assert 1 == 0
E        +  where 1 = <Result SystemExit(1)>.exit_code
/builddir/build/BUILD/hatch-hatch-v1.0.0rc16/tests/cli/env/test_remove.py:181: AssertionError
----------------------------- Captured stderr call -----------------------------
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f629447d990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest/
WARNING: Retrying (Retry(total=3, …
```

Add requires_internet mark to additional tests

---

backend/src/hatchling/builders/config.py
backend/src/hatchling/builders/plugin/interface.py
docs/config/build.md
docs/history.md
hatch.toml
tests/backend/builders/test_config.py

Add `skip-excluded-dirs` build option

---

tests/backend/dep/test_core.py

I didn’t notice these before because I had the idea that the tests in `tests/backend` belonged strictly to Hatchling and shouldn’t be run in the Hatch RPM build on Fedora Linux—but I’ve been re-thinking that, and so I found a few more tests that I missed handling in #171.
In offline build environments, fixes six test failures similar to:
```
>               raise CalledProcessError(retcode, process.args,
output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '['pip', 'install', 'requests[security]==2.25.1']' returned non-zero exit status 1.
/usr/lib64/python3.10/subprocess.py:524: CalledProcessError
```
```
FAILED tests/backend/dep/test_core.py::test_dependency_found - subprocess.Cal...
FAILED tests/backend/dep/test_core.py::test_extra_no_dependencies - …
```

Add the “requires_internet” mark to a few more tests

---

backend/src/hatchling/version/source/code.py

Ensure predefined module attributes are available.
Seen while migrating `jupyterlab/extension-cookiecutter-ts` which uses the `__file__` [attribute](https://github.com/jupyterlab/extension-cookiecutter-ts/blob/d9c1017d2ee76bba1c34368a1ebfb539ef22e00f/%7B%7Bcookiecutter.python_name%7D%7D/%7B%7Bcookiecutter.python_name%7D%7D/_version.py#L7).

Improve module compatibility for CodeSource plugin

---

src/hatch/cli/new/migrate.py

Seen while migrating https://github.com/jupyterlab/extension-cookiecutter-ts.
We have a top level `install.json` file that was being mapped to `/install.json`, which was being interpreted as an absolute file path.
```toml
[tool.hatch.build.targets.wheel.shared-data]
"/install.json" = "share/jupyter/labextensions/test/install.json"
```

Fix handling of top level data_files in migration

---

backend/src/hatchling/builders/wheel.py
docs/history.md
tests/backend/builders/test_wheel.py
tests/helpers/templates/wheel/standard_default_build_script.py
tests/helpers/templates/wheel/standard_default_build_script_artifacts.py
tests/helpers/templates/wheel/standard_default_build_script_artifacts_with_src_layout.py
tests/helpers/templates/wheel/standard_default_build_script_configured_build_hooks.py
tests/helpers/templates/wheel/standard_default_build_script_extra_dependencies.py
tests/helpers/templates/wheel/standard_default_extra_metadata.py
tests/helpers/templates/wheel/standard_default_license_multiple.py
tests/helpers/templates/wheel/standard_default_license_single.py
tests/helpers/templates/wheel/standard_default_namespace_package.py
tests/helpers/templates/wheel/standard_default_python_constraint.py
tests/helpers/templates/wheel/standard_default_shared_data.py
tests/helpers/templates/wheel/standard_default_symlink.py
tests/helpers/templates/wheel/standard_editable_exact.py
tests/helpers/templates/wheel/standard_editable_exact_extra_dependencies.py
tests/helpers/templates/wheel/standard_editable_exact_force_include.py
tests/helpers/templates/wheel/standard_editable_pth.py
tests/helpers/templates/wheel/standard_editable_pth_extra_dependencies.py
tests/helpers/templates/wheel/standard_editable_pth_force_include.py
tests/helpers/templates/wheel/standard_entry_points.py
tests/helpers/templates/wheel/standard_only_packages_artifact_override.py
tests/helpers/templates/wheel/standard_tests.py

So `importlib.metadata` can avoid a read

Don't write empty entry points file for `wheel` targets if there are no entry points defined

---

hatch.toml
pyproject.toml

https://pypi.org/project/bandit
https://bandit.readthedocs.io/en/latest/config.html
It would also be possible to add `-q, --quiet, --silent -- only show output in the case of an error`

Add bandit: A security oriented static analyser

---

docs/history.md
pyproject.toml
src/hatch/config/user.py
src/hatch/config/utils.py
src/hatch/utils/fs.py

https://github.com/untitaker/python-atomicwrites/issues/61

Remove `atomicwrites` dependency

---

docs/history.md
docs/plugins/publisher/reference.md
docs/publish.md
src/hatch/cli/application.py
src/hatch/cli/publish/__init__.py
src/hatch/cli/terminal.py
src/hatch/publish/plugin/interface.py
tests/cli/publish/test_publish.py
tests/publish/plugin/test_interface.py

Add a way to require confirmation for publishing

---

backend/src/hatchling/builders/plugin/interface.py
backend/src/hatchling/builders/sdist.py
backend/src/hatchling/builders/wheel.py
docs/history.md
docs/plugins/builder/sdist.md
docs/plugins/builder/wheel.md
tests/backend/builders/test_sdist.py
tests/backend/builders/test_wheel.py

Add `strict-naming` option for  `sdist` and `wheel` targets

---

docs/history.md
src/hatch/cli/run/__init__.py
tests/cli/run/test_run.py

Support `-h`/`--help` flag for the `run` command

---

backend/src/hatchling/version/source/code.py
docs/history.md
docs/plugins/version-source/code.md
tests/backend/version/source/test_code.py

Many packages rely on `python setup.py ...` putting the current directory in `sys.path` https://github.com/pypa/hatch/issues/338#issuecomment-1179639559
Thus the `search-paths` option, which is necessary to port Django https://github.com/django/django/blob/4.0.6/django/__init__.py

Improve the `code` version source

---

backend/src/hatchling/builders/wheel.py
docs/history.md
tests/backend/builders/test_wheel.py
tests/helpers/templates/wheel/standard_no_strict_naming.py

The `strict-naming` option now also applies to the metadata directory of `wheel` targets

---

docs/history.md
src/hatch/utils/shells.py

`spawn_linux_shell` was using the original dimensions to update the terminal window size instead of retrieving the current dimensions. Based on the notes in the [`pexpect.interact` documentation] using `shutil` to retrieve the size instead of `ioctl`.
I couldn't find a test suite associated with the shell spawning functionality so I modified my local installed copy and verified the functionality.
This PR addresses #381 .
[`pexpect.interact` documentation]: https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.interact

Retrieve current window size in SIGWINCH handler

---

backend/src/hatchling/metadata/core.py
docs/history.md
tests/backend/metadata/test_core.py

resolves:
- https://github.com/NTIA/tekrsa-api-wrap/pull/10
- https://github.com/NTIA/scos-tekrsa/pull/21

Note the `allow-direct-references` option in the relevant error messages

---

docs/history.md
docs/plugins/publisher/package-index.md
docs/publish.md
src/hatch/config/model.py
src/hatch/publish/index.py
tests/cli/config/test_show.py
tests/cli/publish/test_publish.py
tests/config/test_model.py

The `index` publisher now recognizes repository-specific options

---

src/hatch/utils/shells.py

When using hatch on Windows (git bash), `hatch shell` throws exception about `pexpect.spawn()` not supported on Windows. I am not sure if it is the correct way, but it seems to work. Any suggestion?

Enable invocation of bash for `hatch shell` on Windows

---

docs/assets/css/custom.css
mkdocs.yml

The `mkdocstrings` handler for python's version is outdated.
Changes:
1. update the latest recommended-style-material: https://mkdocstrings.github.io/python/customization/#recommended-style-material
2. `watch` deprecated since version 0.19 https://mkdocstrings.github.io/usage/#watch-directories

Update mkdocstrings config

---

backend/src/hatchling/metadata/core.py
docs/config/metadata.md
docs/history.md
tests/backend/metadata/test_core.py
tests/backend/metadata/test_hatch.py

resolves https://github.com/pypa/hatch/issues/274
also required by Twisted https://github.com/twisted/twisted/pull/11656

Add deprecated option to allow ambiguous features

---

src/hatch/cli/env/show.py
src/hatch/utils/dep.py
tests/cli/env/test_show.py

PR adds in support for context formatting in the `hatch env show` command.
Not sure if this is the best way to do it, but it does this by modifying `hatch.utils.dep.get_normalized_dependencies` by adding an optional `context` kwarg which (if provided) runs context formatting on the dependencies list, passing the kwarg in for the env show cli call.
Also added a test with a project that has an environment `foo` with `{'extra-dependencies': ['bar @ {root:uri}/bar', 'baz']}`, the expected result is:
```
Standalone                           
+---------+---------+-----------------------------------------+
| Name    | Type    | Dependencies                            |
+=========+=========+=========================================+
| default | virtual |                                         | …
```

Context Formatting Support for Environments

---

docs/config/build.md

The "editable installs" section was moved to a different page in the pip docs.

Update link to "editable installs" in build docs

---

backend/src/hatchling/version/scheme/standard.py
docs/history.md
docs/plugins/version-scheme/standard.md
tests/backend/version/scheme/test_standard.py

Add `validate-bump` option to the `standard` version scheme

---

backend/src/hatchling/builders/config.py
backend/src/hatchling/builders/wheel.py
docs/history.md
docs/plugins/utilities.md
tests/backend/builders/test_config.py
tests/backend/builders/test_wheel.py

Fix default file selection behavior of the `wheel` target when there is a single top-level module

---

docs/blog/posts/release-hatch-160.md
docs/config/environment/advanced.md
docs/environment.md
docs/history.md
docs/meta/faq.md
hatch.toml
src/hatch/cli/env/run.py
src/hatch/cli/run/__init__.py
src/hatch/template/files_default.py
tests/helpers/templates/new/default.py
tests/helpers/templates/new/feature_cli.py
tests/helpers/templates/new/feature_src_layout.py
tests/helpers/templates/new/licenses_empty.py
tests/helpers/templates/new/licenses_multiple.py
tests/helpers/templates/new/projects_urls_empty.py
tests/helpers/templates/new/projects_urls_space_in_label.py

tox/virtualenv only support the shortened Python version format for legacy reasons

Update best practices part 1

---

.github/workflows/test.yml
backend/src/hatchling/build.py
backend/src/hatchling/ouroboros.py
docs/meta/authors.md
pyproject.toml

As https://github.com/pypa/hatch/issues/564, I start to add type hints in the `backend/hatchling` part, first `build.py` and `ouroboros.py`.
Use `mypy` overrides config to add module check until all files are checked, then we can remove this.
```toml
[[tool.mypy.overrides]]
module = [
"backend.src.hatchling.build",
"backend.src.hatchling.ouroboros"
]
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_no_return = true
```

Mypy check build.py and ouroboros.py

---

backend/src/hatchling/metadata/spec.py
docs/history/hatch.md
tests/backend/metadata/test_spec.py

resolves https://github.com/pypa/hatch/issues/569

Retroactively support `License-Expression` core metadata

---

backend/src/hatchling/metadata/core.py
backend/src/hatchling/metadata/utils.py
docs/meta/authors.md

Part of https://github.com/pypa/hatch/issues/564
Originally I removed the initialisation of attributes used to store property values and instead used `getattr` calls for it, as this avoids having to type-hint attributes which shouldn't be accessed as the property would should always be called anyway, but that does obscure some of the logic a bit so I changed it back to just type hinting all the attributes used for lazy properties.
This is the commit before that change https://github.com/pypa/hatch/commit/1a095f48bb936a8eabec682c8120f116449fb2cb if anybody prefers that style I'm happy to move back as well. It has some benefits but in this case the extra verbosity is probably worth having just to make it very clear what's going on.

Add type hints for hatchling.metadata

---

docs/config/project-templates.md
docs/environment.md
docs/intro.md
docs/version.md
pyproject.toml
src/hatch/template/files_default.py
src/hatch/template/files_feature_cli.py
tests/helpers/templates/new/basic.py
tests/helpers/templates/new/default.py
tests/helpers/templates/new/feature_cli.py
tests/helpers/templates/new/feature_no_src_layout.py
tests/helpers/templates/new/licenses_empty.py
tests/helpers/templates/new/licenses_multiple.py
tests/helpers/templates/new/projects_urls_empty.py
tests/helpers/templates/new/projects_urls_space_in_label.py

- Improve coverage, waiting on https://github.com/pytest-dev/pytest-cov/pull/508
- Add [Black](https://github.com/psf/black)
- Add [Ruff](https://github.com/charliermarsh/ruff)
- Add [Mypy](https://github.com/python/mypy)
Enforces absolute imports for easy addition of Mypyc if the user wants to eventually

Update templates for new projects

---

backend/src/hatchling/builders/wheel.py
docs/history/hatchling.md
tests/backend/builders/test_wheel.py

resolves https://github.com/ofek/hatch-mypyc/issues/24

Acknowledge the `ARCHFLAGS` environment variable on macOS

---

src/hatch/utils/fs.py

Hi!
Two unit tests (test_config_file_creation_verbose, test_config_file_creation_default) fail on my machine because I have separate partitions for "/home" and "/". The /tmp directory where the tests write the necessary files is in one partition, and the hatch configuration file is in another. I did a bit of research and it seems the solution is to replace pathlib.replace with shutils.move.
Alternatively, I could keep the original code and try to handle it in a exception clause of OSError (assuming i can identify the error type as "invalid cross link device"). Please tell me how to prefer it.

Fix test suite for setups with separate "/home" and "/" disk partitions

---

docs/history/hatch.md
src/hatch/cli/config/__init__.py
tests/cli/config/test_set.py

I was trying to use the CLI `hatch config set template.licenses.header false`, but no matter what I typed (`false`, `False`, `0`, `"false"` etc), I kept receiving the error "must be a boolean" which originates from here https://github.com/pypa/hatch/blob/d3eeb62a0c094681d30284a084d6a7c50f8864a6/src/hatch/config/model.py#L569-L581
Originally I tried to fix the issue by doing a type cast after line 573 in `hatch/src/hatch/config/model.py`, while this got rid of the error, it resulted in the output to the console being wrong; ie `"FalSe"` was cast to `False` and I think the underlying model was updated correctly, but the console would show:
```text
New setting:
[template.licenses]
headers = "FalSe"
```
So instead I tried to fix the issue in `src/hatch/cli/config/__init__.py` in a bit of a …

Support boolean values for the `config set` command

---

.github/workflows/test.yml

This patch is intended to lower the maintenance burden of having to manually go through each matrix subjob name in the branch protection repository settings. It allows to only include the `check` job in the branch protection and it will robustly determine if the dependencies have succeeded or not.
It is currently mostly serves the Python ecosystem in projects like aiohttp, attrs, cryptography, pydantic, open edX, pip etc. But I've also seen other communities picking it up lately, like the AWS Rust SDK and even the engine powering https://dev.to, to my surprise. Strictly speaking, it is agnostic.
Ref: https://github.com/marketplace/actions/alls-green#why

Introduce a centralized GHA check/gate job

---

backend/src/hatchling/metadata/classifiers.py

* Add `Environment :: WebAssembly` and `Framework :: Pydantic` to valid [PyPI trove classifiers](https://pypi.org/classifiers/).
- c.f. https://discuss.python.org/t/do-we-want-classifiers-for-webassembly-on-pypi/22712
This was only very recently added in https://github.com/pypa/trove-classifiers/pull/129.
Closes #727 (duplicate).

feat: Add Environment :: WebAssembly and Framework :: Pydantic to trove classifiers

---

src/hatch/cli/new/__init__.py
src/hatch/cli/new/migrate.py
tests/cli/new/test_new.py

`hatch new --init` did not do its Setuptools migration thing if there was no `setup.py` present, even if a `setup.cfg` was (which is a valid configuration when `setuptools` is the builder configured in `pyproject.toml`).
This makes it... do its thing. 😁

Allow hatch new --init without setup.py if setup.cfg is present

---

src/hatch/cli/new/migrate.py

When PYTHONSAFEPATH is non-empty, current dir is not added automatically. So the setuptools shim was not found. By appending the dir in PYTHONPATH, we make sure it's found.
Closes #769

fix: add dir in PYTHONPATH for `hatch new --init`

---

backend/src/hatchling/dep/core.py
tests/backend/dep/test_core.py
tests/conftest.py

This pull request improve syncing of dependencies provided through git URLs, cf. issue https://github.com/pypa/hatch/issues/760
This implementation uses `subprocess.run` to run the `git` command to retrieve the latest commit for a git repository branch. It should support most cases mentioned in https://peps.python.org/pep-0440/#direct-references 
I added 3 tests for git URL dependencies in `tests/backend/dep/test_core.py` which raises the coverage for this file from 61% to 91%. 
⚠️ The `git` command needs to be present in the test environment for the tests to pass. So I added a pytest mark `requires_git`  that checks `subprocess.check_call(['git', 'help'])`, and skip the test if a status code different than 0 is returned
I made sure to run the following scripts:
- `cov`
- `lint:fmt`
- …

Improve syncing of dependencies provided through git URLs

---

backend/src/hatchling/metadata/classifiers.py

PyPI already has packages under new classifier:
- https://pypi.org/search/?c=Framework+%3A%3A+Django+%3A%3A+4.2
- https://pypi.org/classifiers/
New version is about to be released in April, while we already have 4.2b1 beta release version.

feat: Add Django 4.2 to the list of classifiers

---

backend/src/hatchling/metadata/core.py
tests/backend/metadata/test_core.py

https://github.com/pypa/hatch/issues/790
Remove line breaks from the description field if have.

Normaliza metadata the description field when contain line break

---

docs/config/hatch.md

The [`platformdirs`](https://pypi.org/project/platformdirs/) module used to find the default platform-specific config directory looks in a different directory than what is specified in the docs.

fix(docs): default `config.toml` location on macOS

---

docs/version.md

Noticed while trying to follow along with the versioning documentation that the example custom `pattern` would return only empty-string as the `version` match. (My late-night brain did not immediately realize why the output of `hatch version` was blank, but I got there in the end.)
My edited example is a simplistic pattern that matches whatever happens to be there, attempting no validation of the version number format.

docs: functional custom version pattern example

---

pyproject.toml
src/hatch/template/files_default.py
tests/helpers/templates/new/default.py
tests/helpers/templates/new/feature_cli.py
tests/helpers/templates/new/feature_no_src_layout.py
tests/helpers/templates/new/licenses_empty.py
tests/helpers/templates/new/licenses_multiple.py
tests/helpers/templates/new/projects_urls_empty.py
tests/helpers/templates/new/projects_urls_space_in_label.py

It’s derived from `requires-python` in both Ruff:
> ## [target-version](https://beta.ruff.rs/docs/settings/#target-version)
> […]
> If omitted, and Ruff is configured via a `pyproject.toml` file, the target version will be inferred from its `project.requires-python` field (e.g., `requires-python = ">=3.8"`).
and Black (in https://github.com/psf/black/pull/3219):
> ## [`-t`, `--target-version`](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#command-line-options)
> […] By default, Black will try to infer this from the project metadata in pyproject.toml. […]

Use derived target version

---

src/hatch/cli/application.py
src/hatch/cli/build/__init__.py
src/hatch/cli/env/prune.py
src/hatch/cli/env/remove.py
src/hatch/cli/new/__init__.py
src/hatch/cli/project/metadata.py
src/hatch/cli/terminal.py
src/hatch/cli/version/__init__.py

I use this in an upcoming PR. This will be available to plugin authors

Add nestable terminal status utility

---

.github/workflows/build-hatch.yml

Installers like an MSI should be the only way to upgrade/downgrade/remove installations that have already been installed that way

Only enable management commands for standalone binaries

---

docs/environment.md

Updated environment.md example command using cowsay. Cowsay commands now need a -t flag in version 6+. This is referring to the issue #993.

Fix example in docs

---

src/hatch/publish/index.py
tests/cli/publish/test_publish.py

Fixes https://github.com/pypa/hatch/issues/998

Propose `__TOKEN__` as default when prompting a username for `hatch publish`

---

.github/workflows/test.yml
src/hatch/template/files_default.py
src/hatch/template/files_feature_ci.py
tests/cli/project/test_metadata.py
tests/helpers/templates/new/basic.py
tests/helpers/templates/new/default.py
tests/helpers/templates/new/feature_ci.py
tests/helpers/templates/new/feature_cli.py
tests/helpers/templates/new/feature_no_src_layout.py
tests/helpers/templates/new/licenses_empty.py
tests/helpers/templates/new/licenses_multiple.py
tests/helpers/templates/new/projects_urls_empty.py
tests/helpers/templates/new/projects_urls_space_in_label.py

Hi there :wave: 
I just started using Hatch for the first time and I'm having a really great experience! I noticed that Python 3.12 isn't currently included in `pyproject.toml`/the template Github Action workflows, so I've added them here. Hope I didn't miss anything!

feat: update templates to include Python 3.12

---

src/hatch/env/virtual.py

Fix handling of metadata and Python resolution

---

docs/plugins/builder/wheel.md

The sentence was previously ambiguous and wasn't clear whether the "Python" adjective referred to the "file" noun as well.
In fact all non-.py files are included, so reword slightly to better clarify.

Clarify default file selection for wheels

---

docs/environment.md

How to add dependencies in more detail

---

docs/community/contributing.md
mkdocs.yml

@ofek  This PR adds a **contributing** page to the **community** section to detail the recommended process to make a contribution to hatch
The process is relatively straightforward and well defined, but it is always a bit tedious to go decrypt the scripts in the `pyproject.toml`/`hatch.toml` to remember how to run the tests, linting or doc generation
Adding a contributing page would make the process smoother and encourage newcomers to contribute (also it's a nice way to show how clean a development process can be when using `hatch`!)
This have been asked about at least in 1 issue afaik: https://github.com/pypa/hatch/issues/835
I am not sure this should go to **community**, or **meta**, or **How-to** though (feel free to move it if necessary)

Add a contributing page

---

backend/src/hatchling/builders/config.py
docs/config/build.md
docs/history/hatchling.md
tests/backend/builders/test_config.py

Supersedes #983 
Resolves #802

Allow using an empty string for the `sources` option to add a prefix to distribution paths

---

.github/workflows/build-hatch.yml

https://github.com/pypa/hatch/pull/973 was a mistake, people don't want that.
To revert, I basically copied the code of the workflow file from before that commit then applied manually:
- https://github.com/pypa/hatch/commit/6a1f8dca0d9df3f2bbea6f3c7e8c509ec234da75
- https://github.com/pypa/hatch/commit/68c8cafd0b922395462736d8d1bd5579ce1db5d5
- https://github.com/pypa/hatch/commit/86393f9a69a4a0a7e8acf9c3efc6814d224ccd75
Additionally, there has been a new release of apple-codesign which fixes the bug that has plagued us so we now use that rather than artifacts from their CI

Allow management commands for installer binaries

---

src/hatch/template/files_default.py
tests/helpers/templates/new/default.py
tests/helpers/templates/new/feature_cli.py
tests/helpers/templates/new/feature_no_src_layout.py
tests/helpers/templates/new/licenses_empty.py
tests/helpers/templates/new/licenses_multiple.py
tests/helpers/templates/new/projects_urls_empty.py
tests/helpers/templates/new/projects_urls_space_in_label.py

I don't want to do `type` because that is too similar to a built-in of the Windows command prompt

Change the name of the type checking environment in new project templates

---

.github/workflows/build-hatch.yml
docs/install.md
pyoxidizer.bzl

I wanted to figure out how to cross compile Windows ARM but that will come in the next release since I don't have time

Remove 32-bit builds for Windows

---

backend/src/hatchling/builders/wheel.py
docs/history/hatchling.md
tests/backend/builders/test_wheel.py

Resolves https://github.com/pypa/hatch/issues/1054

Fix the `wheel` target for case insensitive file systems

---

ruff_defaults.toml
scripts/update_ruff.py
src/hatch/env/internal/fmt.py
tests/backend/builders/plugin/test_interface.py
tests/backend/builders/test_wheel.py
tests/backend/dep/test_core.py
tests/cli/env/test_create.py
tests/cli/fmt/test_fmt.py
tests/cli/new/test_new.py
tests/cli/project/test_metadata.py
tests/cli/publish/test_publish.py
tests/cli/python/conftest.py
tests/cli/python/test_install.py
tests/cli/run/test_run.py
tests/conftest.py
tests/python/test_core.py
tests/utils/test_platform.py

https://github.com/astral-sh/ruff/issues/8796

Update Ruff rules

---

backend/src/hatchling/cli/build/__init__.py
ruff.toml
src/hatch/cli/build/__init__.py
src/hatch/venv/core.py
tests/cli/build/test_build.py
tests/venv/test_core.py

https://github.com/astral-sh/ruff/issues/8627

Fix Ruff file exclusion

---

backend/src/hatchling/utils/fs.py
docs/history/hatchling.md
tests/backend/utils/test_fs.py

I originally thought about using [urllib.parse.quote](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) but I think other special characters are actually fine for file system URIs.
Resolves #1096

Properly escape spaces for URI context formatting

---

backend/src/hatchling/builders/config.py
backend/src/hatchling/builders/wheel.py
docs/history/hatchling.md
tests/backend/builders/test_wheel.py

Consider forced inclusion patterns and build-time artifacts as file selection

---

backend/src/hatchling/metadata/spec.py
tests/backend/metadata/test_spec.py

`dependency` can be a valid spec with an `or` operation, and adding the `and extra` to that statement will break it.
This PR always wraps the environment markers with parenthesis to prevent this, and updates existing tests to expect the parenthesis.
Fixes #1131.

Add parenthesis around dependencies with extras

---

docs/plugins/metadata-hook/reference.md

UniDep is a tool that allows for a single source of truth when working in projects that have both conda and pip dependencies.
It supports Hatchling: https://github.com/basnijholt/unidep?tab=readme-ov-file#hatchling-integration

Add UniDep to metadata-hook plugins

---

backend/src/hatchling/utils/context.py
docs/config/context.md
docs/history/hatchling.md
tests/backend/utils/test_context.py

Add a new `:parent` modifier for path. This can be specified any numbers of times, with each addition stripping one level from the path.
This is useful in the context of a monorepo to help normalise paths between sibling packages.
Resolves: #825

Add `:parent` path modifier

---

tests/cli/build/test_build.py
tests/cli/project/test_metadata.py
tests/cli/version/test_version.py

Three of the four `test_no_compatibility_check_if_exists` tests fail, and the captured `stderr` contains a network-related error, in an offline build for Fedora Linux. This adds the `requires_internet` mark to those tests.

Add the requires_internet mark to a few tests

---

docs/history/hatch.md
src/hatch/cli/application.py
tests/cli/run/test_run.py

resolves #1168 
This PR updates `dependency_hash` on an environment after `dependencies_in_sync` / `sync_dependencies` have been called.

fix: updated dependency hash

---

docs/history/hatch.md
docs/plugins/environment/reference.md
src/hatch/cli/application.py
src/hatch/env/plugin/interface.py
tests/cli/env/test_create.py

@juftin Curious your thoughts on this

Add life cycle messaging methods to the `environment` interface

---

docs/.hooks/title_from_content.py
mkdocs.yml

* Refs https://github.com/mkdocs/mkdocs/issues/3532#issuecomment-1902757023
Caveat: this uses a private attribute, the next version of MkDocs will probably have something official instead

Docs: extract title from content

---

backend/src/hatchling/builders/wheel.py
tests/backend/builders/test_wheel.py

This PR attempts to (further 😁) improve the messaging for the "nothing to package in a wheel" situation by adding the inferred package name to the message.

Improve error message for #1089

---

docs/.snippets/links.txt

fixes broken [PEP 665](https://peps.python.org/pep-0665/) link, adding it to where the snippet including other PEP links.
In use on https://hatch.pypa.io/1.9/meta/faq/ which is  https://github.com/pypa/hatch/blob/c20358d120d24afebc14bb4f51a75bb426989b33/docs/meta/faq.md?plain=1#L21

Update links.txt - missing PEP 665 in use on FAQ

---

docs/community/contributing.md

@ofek i hope it's ok to just submit a tiny pr like this without an issue. i kept trying to run the docs build:check command and it was failing. and then i realized it was just a small typo in the contributing file. 
this PR just fixes that one file. Now i can check things locally. I'll try to fix the warning in my other open PR next.

Fix: minor typo in contributing file

---

docs/how-to/config/dynamic-metadata.md
docs/plugins/metadata-hook/custom.md
mkdocs.yml

Here's my guide to creating a custom metadata plugin.  Some questions and uncertainties indicated in parentheses in the text.
This may generalize to other plugins, but I tried to stick close to what I knew worked.

Draft How-To for custom dynamic metadata

---

backend/src/hatchling/builders/config.py
tests/backend/builders/test_config.py

Whitelists are possible in the vcs configuration.
These whitelists would override any configured
exclusions.
Configured exclusion should take precedence over
vcs configuration.
Issue #1276

Add vcs exclude patterns before other patterns.

---

src/hatch/cli/application.py
src/hatch/cli/publish/__init__.py

This PR passes the `Application` object to the `environment` and `publish` plugins instead of the `SafeApplication`. Having access the the `Application` object in an environment plugin can be extremely powerful.
In this case [hatch-pip-compile](https://github.com/juftin/hatch-pip-compile) would like access to the `Application.prepare_environment` and `Application.get_environment` functionality so that an environment can create its "constraint" environment (a `hatch-pip-compile` concept where environments can use each others lockfiles as constraints).
Relates to #1227 - I figured I'd create a PR out of it as well. 
I understand the `SafeApplication` likely has "safe" in the name for a reason - what was the original reason to create the `SafeApplication`? In particular I'm interested in …

remove safe application

---

backend/src/hatchling/builders/wheel.py
docs/history/hatchling.md
tests/backend/builders/test_wheel.py
tests/helpers/templates/wheel/standard_default_python_constraint_three_components.py

Prior to this PR, a `requires-python` version constraint of three components (e.g. `==3.11.4`) caused hatchling to fail detecting the supported Python versions and create invalid wheel filenames such as `mypackage-0.1.0--none-any.whl`. This fix takes micro versions into account as well and produces for the above three components version constraint the expected filename `mypackage-0.1.0-py3-none-any.whl`.
Related discussion: https://github.com/pypa/hatch/discussions/1277

fix: respect three components Python version

---

docs/history/hatch.md
src/hatch/cli/fmt/__init__.py

Resolves https://github.com/pypa/hatch/issues/1379

Fix the `fmt` command when automatically installing plugin dependencies

---

backend/src/hatchling/metadata/core.py
backend/src/hatchling/metadata/utils.py
docs/history/hatchling.md
tests/backend/metadata/test_core.py

Resolves https://github.com/pypa/hatch/issues/1347

Support recursive optional dependencies

---

backend/src/hatchling/builders/constants.py
docs/history/hatchling.md

https://github.com/pypa/packaging-problems/issues/751

Add `.venv` to the list of directories that cannot be traversed

---

docs/history/hatch.md
src/hatch/template/files_default.py
tests/helpers/templates/new/basic.py
tests/helpers/templates/new/default.py
tests/helpers/templates/new/feature_cli.py
tests/helpers/templates/new/feature_no_src_layout.py
tests/helpers/templates/new/licenses_empty.py
tests/helpers/templates/new/licenses_multiple.py
tests/helpers/templates/new/projects_urls_empty.py
tests/helpers/templates/new/projects_urls_space_in_label.py
tests/helpers/templates/sdist/standard_include.py
tests/helpers/templates/sdist/standard_include_config_file.py

Resolves https://github.com/pypa/hatch/pull/1409
Supersedes https://github.com/pypa/hatch/pull/1409

Fix the `README.md` file template for new projects to avoid Markdown linting issues

---

backend/src/hatchling/builders/wheel.py
docs/plugins/builder/wheel.md
tests/backend/builders/test_wheel.py

Users cannot get macOS 12+ as a minimum with this forcing 10.16.
I'd like to make https://github.com/pypa/hatch/issues/1445 a followup, as users might need to target an older macOS than the one they are running (cibuildwheel always does this, for example).

fix: swap default for macos-max-compat

---

src/hatch/cli/application.py
src/hatch/cli/python/install.py
src/hatch/utils/shells.py
tests/cli/python/conftest.py

Before this fix some of the internal hatch tests were failing when invoked from zsh shell. This change updates the test fixture to use the same shell detection mechanism as in the actual hatch code.
One of the test errors before the fix:
```
E       AssertionError: expected call not found.
E       Expected: append('/private/var/folders/q3/s01nm0vn50n3696zg_w711yr0000gn/T/tmpuovbeire/data/pythons/pypy3.9/pypy3.9-v6.3.15-macos_arm64/bin', shells=['sh'])
E         Actual: append('/private/var/folders/q3/s01nm0vn50n3696zg_w711yr0000gn/T/tmpuovbeire/data/pythons/pypy3.9/pypy3.9-v6.3.15-macos_arm64/bin', shells=['zsh'])
E
E       pytest introspection follows:
E
E       Kwargs:
E       assert {'shells': ['zsh']} == {'shells': ['sh']}
E
E         Differing items:
E         {'shells': ['zsh']} != …
```

Fix internal tests invoked from zsh shell

---

docs/history/hatch.md
src/hatch/cli/config/__init__.py
src/hatch/cli/terminal.py

Resolves https://github.com/pypa/hatch/issues/1465

Fix syntax highlighting contrast for the `config show` command

---

backend/src/hatchling/builders/sdist.py
backend/src/hatchling/builders/utils.py
backend/src/hatchling/builders/wheel.py
tests/backend/builders/test_sdist.py
tests/backend/builders/test_wheel.py
tests/helpers/templates/wheel/utils.py

fixes #1519.
currently hatchling just inherits a 700 on each from tempfile.mkstemp, which isn't particularly friendly to CI/build systems. We apply normalize_file_permissions to set the output artifacts to 644.
wrt tests, I just copypasta'd another one to add a new test explicitly for the perms test; if you'd like i can just remove and tack the logic into one of the existing tests instead (I couldn't find one that seemed specific enough).

normalize sdist/wheel artifact file perms

---

backend/src/hatchling/builders/macos.py
backend/src/hatchling/builders/wheel.py
tests/backend/utils/test_macos.py

Fix #1445.
This respects `MACOSX_DEPLOYMENT_TARGET` if set (which it is by tools like cibuildwheel).
I didn't add any warnings or logging; scikit-build-core logs details about how it selected things.

fix: macos deployment target selection

---

docs/community/contributing.md

Fixes #1657
Equivalent to the `hatch run` commands, but `hatch run full` is implemented. I checked version 1.7.0 of Hatch and find out that `hatch run full` script runs `pytest --cov --cov-report={env:COVERAGE_REPORT:term-missing} --cov-config=pyproject.toml -n auto --reruns 5 --reruns-delay 3 -r aR {args:tests}` (https://github.com/pypa/hatch/blob/46a2118ba39c00ca102cf463bdc829301402d05b/hatch.toml#L20C1-L23C69). I didn't figure out what is the equivalent of the `hatch run full` script. Do you have any idea?

docs: fix outdated `hatch run` commands

---

.github/workflows/test.yml

Version [v4.4.0](https://github.com/actions/upload-artifact/releases/tag/v4.4.0) of actions/upload-artifact broke uploading (silently) and combining coverage files.

Use `include-hidden-files: true` to upload coverage artifacts

---

tests/cli/env/test_create.py

The tests are failing on `main` with:
```python
env_dirs = list(storage_path.iterdir())
assert len(env_dirs) == 2
env_path = env_dirs[1]
>       assert env_path.name == 'test'
E       AssertionError: assert 'hatch-build' == 'test'
E         
E         - test
E         + hatch-build
/home/runner/work/hatch/hatch/tests/cli/env/test_create.py:1568: AssertionError
```
Not sure what triggered this (perhaps something on the runner changed?), and I couldn't reproduce it locally, but the result of `list(storage_path.iterdir())` was returning `['test', 'hatch-build']` instead of `['hatch-build', 'test']`. Indeed, the docstring of `iterdir` states:
> The children are yielded in arbitrary order
so technically the sort is needed, even if it normally comes out in alphabetical order.

Fix failing test due to unsorted iterdir

---

backend/src/hatchling/builders/constants.py

[Pixi](https://pixi.sh) is a recent tool that manages project-specific Conda environments. The environments are created in a cache directory named `.pixi/` under the project root. They should never be included in a Python distribution. For additional discussion, see
<https://github.com/prefix-dev/pixi/issues/2115#issuecomment-2379136870>

Add pixi to excluded directories

---

backend/src/hatchling/builders/config.py

If our project root directory is matched by an exclude pattern we should assume the pattern is invalid as our project root is likely in an ignored build directory of another project.
Should fix: #1641
This is essentially a port of the same technique I [used to fix a similar poetry core bug](https://github.com/python-poetry/poetry-core/pull/611).

Prevent matching bogus parent gitignores

---

backend/src/hatchling/builders/config.py

We need to return an empty list in the event the project root is ignored by a pattern as the project root being ignored means the ignore patterns are not valid for the project.
This got broken when merging #1643.

Return empty list if project root is ignored

---

.github/workflows/build-hatch.yml
backend/src/hatchling/dep/core.py
backend/src/hatchling/metadata/core.py
docs/config/metadata.md
docs/history/hatchling.md

Resolves #1793 
Resolves #1794

Fix breaking changes

---

backend/src/hatchling/metadata/spec.py
docs/history/hatchling.md
tests/backend/metadata/test_spec.py

Resolves https://github.com/pypa/hatch/issues/1804#issuecomment-2469360000
Also resolves https://github.com/squidfunk/mkdocs-material/pull/7692#issuecomment-2467579900 because metadata hooks shouldn't be called when there is nothing dynamic and therefore the population from `PKG-INFO` was lossy

Back-populate string `license` fields

---

pyproject.toml
tests/cli/project/test_metadata.py
tests/dep/test_sync.py

Flit version 3.11 automatically includes license files in the metadata, even if they are not explicitly referenced in the pyproject.toml. Any file matching a license regex, such as the LICENSE.txt generated by hatch new, is included by default. This broke the result output assumption.
UV>=0.5.23 fixed https://github.com/astral-sh/uv/issues/3014

Fix failing tests

---

backend/tests/downstream/integrate.py
src/hatch/cli/application.py
src/hatch/env/plugin/interface.py
tests/helpers/helpers.py

This option is scheduled to be removed in pip 25.1.
* https://ichard26.github.io/blog/2025/01/whats-new-in-pip-25.0/#upcoming-removals
* [pip v25.0 (2025-01-26) Deprecations and Removals](https://github.com/pypa/pip/blob/main/NEWS.rst#deprecations-and-removals)
* https://github.com/pypa/pip/issues/13154

Stop using deprecated `--no-python-version-warning` option

---

src/hatch/cli/env/run.py

With release of click `v8.3.0`, the click module is leaking `click.core.UNSET` where previously `None` was returned.
This is causing the filter option on the run command to fail.
Favoring explicit over implicit, we can avoid that issue without pinning back the click library.
- #2051 Pins the version of `click`.
fixes #2050

Fix: Set default of None for @click.option("--filter", ...)
