pypa/hatch

hatch/cli.py, hatch/commands/__init__.py, hatch/commands/config.py, hatch/commands/init.py, hatch/commands/install.py, hatch/commands/new.py, hatch/commands/uninstall.py
This PR moves a portion of the commands into their own separate files. 
I'll move the rest of the commands into their respective files tomorrow.
=> Refactor commands

AUTHORS.rst
=> Add new contributor to the list of authors. Fixes #26

CONFIG.rst
Clarifies operation of the semver configuration in the config file documentation.
=> Semver docfix for CONFIG.rst

.travis.yml, AUTHORS.rst
pip3 is the executable name, at least right now.
=> Fix Travis builds on macOS

docs/assets/css/custom.css, docs/config/dependency.md
=> Remove FiraCode font

docs/config/environment.md, docs/meta/history.md, src/hatch/env/plugin/interface.py, tests/env/plugin/test_interface.py
Resolves https://github.com/ofek/hatch/discussions/153
=> Add `extra-dependencies` option to environments

backend/src/hatchling/metadata/core.py, docs/config/metadata.md, docs/meta/history.md, tests/backend/metadata/test_core.py, tests/backend/metadata/test_hatch.py
https://github.com/ofek/hatch/pull/152#issuecomment-1061231829
=> Add option to allow the use of direct references for dependencies

docs/config/hatch.md, docs/history.md, src/hatch/utils/platform.py
Resolves https://github.com/ofek/hatch/issues/149
=> Also use the `SHELL` environment variable fallback on Windows systems

backend/src/hatchling/builders/sdist.py, backend/src/hatchling/metadata/core.py, backend/src/hatchling/utils/constants.py, docs/history.md, tests/backend/builders/test_sdist.py, tests/helpers/templates/sdist/standard_include_config_file.py
=> Always include the root `hatch.toml` config file

docs/history.md, src/hatch/cli/dep/__init__.py, tests/cli/dep/show/test_requirements.py
=> Add `dep show requirements` command

backend/src/hatchling/builders/wheel.py, docs/history.md, tests/helpers/templates/wheel/standard_default_build_script.py, tests/helpers/templates/wheel/standard_default_build_script_artifacts.py, tests/helpers/templates/wheel/standard_default_build_script_artifacts_with_src_layout.py, tests/helpers/templates/wheel/standard_default_build_script_force_include.py, tests/helpers/templates/wheel/standard_default_extra_metadata.py, tests/helpers/templates/wheel/standard_default_license_multiple.py, tests/helpers/templates/wheel/standard_default_license_single.py, tests/helpers/templates/wheel/standard_default_namespace_package.py, tests/helpers/templates/wheel/standard_default_python_constraint.py, tests/helpers/templates/wheel/standard_default_shared_data.py, tests/helpers/templates/wheel/standard_default_symlink.py, tests/helpers/templates/wheel/standard_editable_exact.py, tests/helpers/templates/wheel/standard_editable_pth.py, tests/helpers/templates/wheel/standard_only_packages_artifact_override.py, tests/helpers/templates/wheel/standard_tests.py
=> Change the `Generator` name of wheel metadata from `hatch` to `hatchling`

docs/config/environment.md, docs/history.md, src/hatch/cli/application.py, tests/cli/run/test_run.py
=> Ignore exit code of commands that start with a hyphen

docs/history.md, src/hatch/cli/new/__init__.py, src/hatch/cli/new/migrate.py
=> Improve `setuptools` migration script

docs/config/hatch.md, docs/history.md, hatch.toml, src/hatch/cli/shell/__init__.py, src/hatch/config/model.py, src/hatch/env/plugin/interface.py, src/hatch/env/virtual.py, src/hatch/utils/shells.py, tests/config/test_model.py
=> Support overriding the default arguments used to spawn shells on non-Windows systems

docs/config/build.md
=> Improve artifacts documentation

docs/config/metadata.md
=> Improve entry points documentation

backend/src/hatchling/builders/config.py, docs/config/build.md, docs/config/context.md, docs/config/dependency.md, docs/config/environment/advanced.md, docs/config/environment/overview.md, docs/config/hatch.md, docs/environment.md, docs/next-steps.md, docs/plugins/build-hook.md, docs/plugins/environment-collector.md, docs/plugins/environment.md, mkdocs.yml, src/hatch/env/plugin/interface.py
=> refactor docs for environment configuration

backend/src/hatchling/builders/config.py, backend/src/hatchling/builders/plugin/interface.py, docs/history.md, tests/backend/builders/plugin/test_interface.py
=> Prevent duplicate file entries from inclusion when using the `force-include` option

docs/history.md, src/hatch/template/__init__.py, tests/cli/new/test_new.py
=> Use `utf-8` for all files generated for new projects

backend/src/hatchling/builders/wheel.py, docs/history.md, docs/plugins/builder/wheel.md, tests/backend/builders/test_wheel.py
=> Respect the `force-include` option for editable installs

backend/src/hatchling/builders/config.py, backend/src/hatchling/builders/plugin/interface.py, backend/src/hatchling/builders/utils.py, backend/src/hatchling/builders/wheel.py, docs/config/build.md, docs/history.md, docs/plugins/build-hook/reference.md, docs/plugins/builder/wheel.md, tests/backend/builders/plugin/test_interface.py, tests/backend/builders/test_config.py, tests/backend/builders/test_wheel.py, tests/helpers/templates/wheel/standard_default_build_script_artifacts_with_src_layout.py, tests/helpers/templates/wheel/utils.py
=> Add `only-include` option

docs/config/hatch.md, docs/history.md, pyproject.toml, src/hatch/cli/shell/__init__.py, src/hatch/utils/shells.py
=> Attempt to use the current shell

docs/history.md, src/hatch/template/files_default.py
=> Escape special characters Git may return in the user name

docs/history.md, src/hatch/cli/__init__.py
https://github.com/pypa/hatch/issues/263
=> Make tracebacks colorful and less verbose

backend/src/hatchling/builders/config.py, backend/src/hatchling/builders/hooks/version.py, backend/src/hatchling/builders/plugin/interface.py, backend/src/hatchling/builders/sdist.py, backend/src/hatchling/builders/wheel.py, backend/src/hatchling/metadata/core.py, backend/src/hatchling/version/core.py, backend/src/hatchling/version/source/code.py, backend/tests/downstream/integrate.py, src/hatch/cli/application.py, src/hatch/cli/env/show.py, src/hatch/cli/new/migrate.py, src/hatch/project/core.py, src/hatch/publish/pypi.py, src/hatch/utils/structures.py, src/hatch/utils/toml.py, tests/cli/new/test_new.py, tests/helpers/helpers.py
[`pyupgrade --py37-plus **/*.py`](https://pypi.org/project/pyupgrade)
=> pyupgrade --py37-plus

docs/history.md, src/hatch/env/plugin/interface.py, src/hatch/project/config.py, src/hatch/project/utils.py, tests/env/plugin/test_interface.py, tests/project/test_config.py
part of https://github.com/pypa/hatch/issues/229#issuecomment-1134982879
=> Support ignoring the exit codes of scripts

docs/history.md, src/hatch/cli/application.py, src/hatch/cli/env/run.py, tests/cli/env/test_run.py
finally resolves https://github.com/pypa/hatch/issues/229#issuecomment-1134982879
=> Add `--force-continue` flag to the `env run` command

tests/cli/test_root.py
after all this time it finally wiped my config back to defaults 😅
=> Fix race condition when running tests in parallel

docs/history.md, pyproject.toml
trying to ship for Conda https://github.com/conda-forge/userpath-feedstock/pull/8
=> Relax constraint on `userpath` dependency

backend/src/hatchling/builders/wheel.py, docs/history.md, tests/helpers/templates/wheel/standard_default_build_script.py, tests/helpers/templates/wheel/standard_default_build_script_artifacts.py, tests/helpers/templates/wheel/standard_default_build_script_artifacts_with_src_layout.py, tests/helpers/templates/wheel/standard_default_build_script_configured_build_hooks.py, tests/helpers/templates/wheel/standard_default_build_script_extra_dependencies.py, tests/helpers/templates/wheel/standard_default_build_script_force_include.py, tests/helpers/templates/wheel/standard_default_extra_metadata.py, tests/helpers/templates/wheel/standard_default_license_multiple.py, tests/helpers/templates/wheel/standard_default_license_single.py, tests/helpers/templates/wheel/standard_default_namespace_package.py, tests/helpers/templates/wheel/standard_default_python_constraint.py, tests/helpers/templates/wheel/standard_default_shared_data.py, tests/helpers/templates/wheel/standard_default_single_module.py, tests/helpers/templates/wheel/standard_default_symlink.py, tests/helpers/templates/wheel/standard_editable_exact.py, tests/helpers/templates/wheel/standard_editable_exact_extra_dependencies.py, tests/helpers/templates/wheel/standard_editable_exact_force_include.py, tests/helpers/templates/wheel/standard_editable_pth.py, tests/helpers/templates/wheel/standard_editable_pth_extra_dependencies.py, tests/helpers/templates/wheel/standard_editable_pth_force_include.py, tests/helpers/templates/wheel/standard_entry_points.py, tests/helpers/templates/wheel/standard_only_packages_artifact_override.py, tests/helpers/templates/wheel/standard_tests.py
https://discuss.python.org/t/pep-639-round-2-improving-license-clarity-with-better-package-metadata/12622/68
=> Support the final draft of PEP 639

backend/src/hatchling/cli/build/__init__.py, docs/history.md, src/hatch/cli/build/__init__.py, tests/cli/build/test_build.py
=> Default to `sdist` and `wheel` targets

backend/src/hatchling/builders/sdist.py, docs/plugins/builder/sdist.md
=> Update docs for the `sdist` target

docs/history.md, src/hatch/cli/env/show.py, tests/cli/env/test_show.py
=> Acknowledge `extra-dependencies` for the `env show` command

docs/history.md, src/hatch/cli/application.py, src/hatch/cli/shell/__init__.py
=> Display help text the first time the `shell` command is executed

backend/tests/downstream/integrate.py, docs/history.md, src/hatch/venv/core.py, tests/venv/test_core.py
=> Fix locating executables within virtual environments on Debian

docs/history.md, src/hatch/template/files_default.py, tests/helpers/templates/new/feature_src_layout.py
=> Fix default code coverage file omission for the src-layout project template option

.github/workflows/auto-merge.yml
Idea from https://rednafi.github.io/reflections/automerge-dependabot-prs-on-github.html
Thanks @rednafi!
=> Enable auto-merge for Dependabot

docs/how-to/plugins/testing-builds.md, mkdocs.yml
=> Add how-to section

backend/src/hatchling/builders/config.py, docs/config/build.md, docs/history.md, tests/backend/builders/test_config.py
Vital for DRY config with Mypyc, similar to `require-runtime-dependencies`
=> Add `require-runtime-features` option

backend/src/hatchling/builders/wheel.py, docs/history.md, tests/backend/builders/test_wheel.py
https://github.com/pfmoore/editables/issues/20
=> edge case error message

docs/history.md, src/hatch/project/config.py, tests/project/test_config.py
=> Fix non-detached inheritance disabling for environments

backend/src/hatchling/cli/version/__init__.py, docs/history.md, src/hatch/cli/version/__init__.py, tests/cli/version/test_version.py
=> Fix check for updating static versions

backend/src/hatchling/metadata/core.py, backend/src/hatchling/metadata/plugin/interface.py, docs/history.md, docs/plugins/metadata-hook/reference.md, tests/backend/metadata/test_core.py
=> Add `get_known_classifiers` method to metadata hooks

docs/environment.md
I did get there - but I think this would have helped!
=> Add link in environment.md from introduction to selection

src/hatch/project/core.py
The issue has already been fixed.
https://github.com/sdispater/tomlkit/pull/50
=> Remove outdated tomlkit workaround

backend/src/hatchling/cli/__init__.py, backend/src/hatchling/cli/metadata/__init__.py, docs/history.md
=> Add `metadata` command to view PEP 621 project metadata

docs/install.md
=> Explicitly recommend install methods with env isolation

docs/users.md
`Tox` pr has been merged into the rewrite branch.
=> Fix doc users tox link

backend/src/hatchling/metadata/spec.py, docs/history.md, tests/backend/metadata/test_spec.py
- https://hatch.pypa.io/1.5/config/dependency/#complex-syntax
- https://github.com/pypa/packaging/issues/529
=> Fix features that use direct references

docs/history.md, src/hatch/cli/dep/__init__.py, src/hatch/cli/terminal.py, src/hatch/env/plugin/interface.py, src/hatch/utils/dep.py
resolves https://github.com/repo-helper/hatch-requirements-txt/issues/9
=> Improve dep commands

backend/src/hatchling/bridge/app.py, backend/src/hatchling/cli/metadata/__init__.py, backend/src/hatchling/cli/version/__init__.py, docs/history.md, src/hatch/cli/application.py, src/hatch/cli/dep/__init__.py, src/hatch/cli/env/find.py, src/hatch/cli/project/metadata.py, src/hatch/cli/version/__init__.py
=> Fix output that should always be displayed

backend/src/hatchling/builders/wheel.py, docs/history.md
resolves https://github.com/pypa/hatch/issues/497
=> Use proper CSV formatting for the `RECORD` metadata file

docs/history.md, src/hatch/cli/publish/__init__.py, src/hatch/publish/index.py, tests/cli/publish/test_publish.py
=> Add `--initialize-auth` flag to the `index` publisher

docs/history.md, docs/plugins/environment/virtual.md, src/hatch/env/virtual.py, tests/cli/env/test_create.py
resolves https://github.com/pypa/hatch/issues/468 https://github.com/pypa/hatch/discussions/117
=> Better support for external auto-detection of environments

docs/history.md, src/hatch/cli/build/__init__.py, src/hatch/cli/project/metadata.py, src/hatch/cli/version/__init__.py, src/hatch/utils/dep.py, tests/cli/build/test_build.py, tests/cli/dep/show/test_requirements.py, tests/cli/dep/show/test_table.py, tests/cli/dep/test_hash.py, tests/cli/project/test_metadata.py, tests/cli/version/test_version.py
=> Check build environment compatibility before use

docs/history.md, src/hatch/cli/env/run.py, tests/cli/run/test_run.py
=> Fix matrix variable inclusion filtering

docs/history.md, src/hatch/template/files_default.py, tests/helpers/templates/new/default.py, tests/helpers/templates/new/feature_cli.py, tests/helpers/templates/new/feature_src_layout.py, tests/helpers/templates/new/licenses_empty.py, tests/helpers/templates/new/licenses_multiple.py, tests/helpers/templates/new/projects_urls_empty.py, tests/helpers/templates/new/projects_urls_space_in_label.py
=> Update the scripts in the generated test environment template

docs/history.md, docs/plugins/utilities.md, src/hatch/env/virtual.py, src/hatch/utils/platform.py, tests/utils/test_platform.py
=> Handle no user home directory

docs/history/hatch.md, src/hatch/cli/__init__.py, src/hatch/cli/application.py, src/hatch/utils/fs.py
resolves https://github.com/pypa/hatch/discussions/546
=> Expand configured cache and data directory paths

.github/workflows/test.yml, src/hatch/template/files_feature_ci.py, tests/helpers/templates/new/feature_ci.py
https://github.com/actions/python-versions/blob/main/versions-manifest.json
=> Upgrade Python in GitHub Actions to 3.11 final

backend/src/hatchling/builders/config.py, backend/src/hatchling/builders/custom.py, backend/src/hatchling/builders/hooks/custom.py, backend/src/hatchling/builders/hooks/plugin/hooks.py, backend/src/hatchling/builders/hooks/plugin/interface.py, backend/src/hatchling/builders/hooks/version.py, backend/src/hatchling/builders/plugin/hooks.py, backend/src/hatchling/builders/plugin/interface.py, backend/src/hatchling/builders/sdist.py, backend/src/hatchling/builders/utils.py, backend/src/hatchling/builders/wheel.py, pyproject.toml
https://github.com/pypa/hatch/issues/564
Add type hints in `hatchling/builders` part. But have some type-hints I'm not sure if it's suitable.
=> Mypy check hatchling/builders

backend/src/hatchling/dep/core.py, pyproject.toml
Add type-hints for `hatchling /dep` part :)
=> Add type-hints for hatchling/dep

docs/history/hatch.md, src/hatch/cli/version/__init__.py, tests/cli/version/test_version.py
=> Fix displaying the version

backend/pyproject.toml, backend/src/hatchling/build.py, backend/src/hatchling/ouroboros.py, docs/history/hatchling.md
=> Store Hatchling's metadata in `pyproject.toml`

backend/src/hatchling/cli/__init__.py, backend/src/hatchling/cli/build/__init__.py, backend/src/hatchling/cli/dep/__init__.py, backend/src/hatchling/cli/metadata/__init__.py, backend/src/hatchling/cli/version/__init__.py, backend/src/hatchling/ouroboros.py, pyproject.toml, tests/cli/publish/test_publish.py
https://github.com/pypa/hatch/issues/564
(And ruff is so fast🚀)
=> Add type-hints for hatchling/cli part

backend/src/hatchling/bridge/app.py, backend/src/hatchling/cli/metadata/__init__.py, backend/src/hatchling/cli/version/__init__.py, docs/history/hatch.md, src/hatch/cli/application.py, src/hatch/cli/config/__init__.py, src/hatch/cli/dep/__init__.py, src/hatch/cli/env/find.py, src/hatch/cli/new/__init__.py, src/hatch/cli/project/metadata.py, src/hatch/cli/terminal.py, src/hatch/cli/version/__init__.py
=> Non-critical output now goes to stderr

backend/src/hatchling/version/core.py, backend/src/hatchling/version/scheme/plugin/hooks.py, backend/src/hatchling/version/scheme/plugin/interface.py, backend/src/hatchling/version/scheme/standard.py, backend/src/hatchling/version/source/code.py, backend/src/hatchling/version/source/env.py, backend/src/hatchling/version/source/plugin/hooks.py, backend/src/hatchling/version/source/plugin/interface.py, backend/src/hatchling/version/source/regex.py, pyproject.toml
https://github.com/pypa/hatch/issues/564
=> Add type-hints for hatchling/version part

docs/community/users.md, docs/plugins/version-scheme/reference.md
=> Update users and known plugins

backend/src/hatchling/builders/wheel.py, docs/history/hatchling.md, docs/plugins/builder/wheel.md, tests/backend/builders/test_wheel.py
=> Add `extra_metadata` build data to the `wheel` target

docs/history/hatch.md, docs/history/hatchling.md, docs/plugins/environment-collector/custom.md, docs/plugins/environment-collector/default.md, mkdocs.yml, src/hatch/env/collectors/custom.py, src/hatch/env/collectors/plugin/hooks.py, src/hatch/plugin/constants.py, tests/env/collectors/test_custom.py, tests/project/test_config.py
To better support very custom scenarios like `nox` can
=> Add `custom` environment collector

src/hatch/template/files_default.py, tests/helpers/templates/new/default.py, tests/helpers/templates/new/feature_cli.py, tests/helpers/templates/new/feature_no_src_layout.py, tests/helpers/templates/new/licenses_empty.py, tests/helpers/templates/new/licenses_multiple.py, tests/helpers/templates/new/projects_urls_empty.py, tests/helpers/templates/new/projects_urls_space_in_label.py
https://github.com/pytest-dev/pytest-cov/issues/337#issuecomment-1328637382
=> Replace pytest-cov with pure coverage in project templates

pyproject.toml, src/hatch/utils/ci.py, src/hatch/utils/dep.py, src/hatch/utils/env.py, src/hatch/utils/fs.py, src/hatch/utils/network.py, src/hatch/utils/platform.py, src/hatch/utils/shells.py, src/hatch/utils/structures.py, src/hatch/utils/toml.py
https://github.com/pypa/hatch/issues/564
=> Add type hints for hatch/utils

backend/src/hatchling/build.py, backend/src/hatchling/ouroboros.py
=> Restore missing default for config_settings

docs/history/hatch.md, src/hatch/env/virtual.py
=> Fix `virtual` build environments

docs/history/hatch.md, docs/plugins/environment/virtual.md, src/hatch/utils/platform.py, tests/utils/test_platform.py
=> Work around System Integrity Protection on macOS

backend/src/hatchling/bridge/app.py, backend/src/hatchling/metadata/core.py, hatch.toml, pyproject.toml, scripts/generate_coverage_summary.py, src/hatch/cli/application.py, src/hatch/cli/env/find.py, src/hatch/cli/env/prune.py, src/hatch/cli/env/remove.py, src/hatch/cli/status/__init__.py, src/hatch/cli/terminal.py, src/hatch/template/default.py, src/hatch/utils/platform.py
So we might sometime get #717 merged...
=> Update ruff baseline to 0.0.259, fix lint errors

backend/src/hatchling/builders/plugin/interface.py, backend/src/hatchling/builders/wheel.py, docs/history/hatchling.md, tests/backend/builders/test_wheel.py
=> Fix dev mode when the project has symlinks

.github/workflows/build-hatch.yml
https://github.com/indygreg/apple-platform-rs/issues/82
=> Fix build flake

.github/workflows/build-hatch.yml, .github/workflows/build-hatchling.yml
https://docs.pypi.org/trusted-publishers/
=> Switch PyPI releasing to the trusted publishing model

.github/workflows/build-hatch.yml
https://github.com/indygreg/apple-platform-rs/issues/82#issuecomment-1598047233
=> Speed up macOS builds

docs/history/hatch.md, src/hatch/utils/shells.py
@flying-sheep Your other PR intrigued me so I tried out that shell today and it's awesome. I [completely switched](https://github.com/nushell/nushell/issues/9403#issuecomment-1704411836) away from xonsh!
Thank you 🙂
=> Fix nushell on Windows

docs/history/hatch.md, docs/plugins/environment/reference.md, src/hatch/cli/application.py, src/hatch/cli/dep/__init__.py, src/hatch/env/plugin/interface.py, src/hatch/utils/dep.py, tests/cli/run/test_run.py
Resolves #730
Resolves #935
Resolves #1001
=> Don't check environments if dependencies have not changed

docs/history/hatch.md, src/hatch/cli/application.py, src/hatch/cli/build/__init__.py, src/hatch/env/internal/__init__.py, src/hatch/env/internal/build.py, src/hatch/env/internal/interface.py, tests/cli/build/test_build.py
=> Support build backends other than Hatchling

docs/plugins/builder/wheel.md
=> Revert "Clarify default file selection for wheels"

backend/src/hatchling/metadata/core.py, tests/backend/metadata/test_core.py
=> Fix console_scripts validation.

docs/plugins/environment/reference.md
https://github.com/juftin/hatch-pip-compile @juftin
=> Add hatch-pip-compile to list of third-party environment plugins

docs/plugins/environment-collector/reference.md
https://github.com/mkdocs/hatch-mkdocs
=>  Add hatch-mkdocs to list of third-party environment collector plugins

docs/.hooks/expand_blocks.py, docs/.hooks/inject_version.py, docs/.hooks/plugin_register.py, docs/.hooks/render_ruff_defaults.py, mkdocs.yml
https://github.com/mkdocs/mkdocs/issues/3486
=> Fix docs build

backend/src/hatchling/builders/config.py, backend/src/hatchling/builders/plugin/interface.py, docs/history/hatchling.md, tests/backend/builders/plugin/test_interface.py, tests/backend/builders/test_wheel.py, tests/helpers/templates/wheel/standard_default_build_script_force_include_no_duplication.py
Resolves https://github.com/pypa/hatch/issues/1030
=> Prevent duplicate paths

mkdocs.yml
@lwasser I believe you asked for this
=> Organize introductory pages

backend/src/hatchling/builders/wheel.py, docs/history/hatchling.md, docs/plugins/builder/wheel.md, tests/backend/builders/test_wheel.py
Resolves https://github.com/pypa/hatch/issues/992
Resolves https://github.com/pypa/hatch/issues/887
=> Require explicit file selection for the `wheel` target

docs/.snippets/links.txt, docs/config/build.md, docs/config/metadata.md, docs/meta/faq.md
Resolves https://github.com/pypa/hatch/issues/942
=> Remove most references to PEP numbers

backend/src/hatchling/builders/wheel.py, docs/history/hatchling.md, tests/backend/builders/test_wheel.py
=> Fix `exclude` counting toward inclusion selection

backend/src/hatchling/builders/wheel.py, docs/history/hatchling.md, tests/backend/builders/test_wheel.py
=> Add `bypass-selection` option to the `wheel` build target

.github/workflows/build-hatch.yml, docs/history/hatch.md, src/hatch/cli/application.py, tests/cli/env/test_create.py, tests/conftest.py
=> Fix automatic installation of environment plugins

docs/config/hatch.md, docs/history/hatch.md, src/hatch/cli/application.py, src/hatch/config/model.py, tests/cli/config/test_show.py, tests/config/test_model.py
https://discuss.python.org/t/announcement-hatch-v1-8-0/40865/6
=> Change default location of Python installations

docs/history/hatch.md, src/hatch/env/internal/fmt.py, tests/cli/fmt/test_fmt.py
=> Properly account for Ruff table already existing

docs/history/hatch.md, src/hatch/cli/application.py, src/hatch/cli/build/__init__.py, src/hatch/cli/env/create.py, src/hatch/cli/env/find.py, src/hatch/cli/env/prune.py, src/hatch/cli/env/remove.py, src/hatch/cli/env/run.py, src/hatch/cli/project/metadata.py, src/hatch/cli/version/__init__.py, src/hatch/env/plugin/interface.py, tests/cli/build/test_build.py, tests/cli/env/test_find.py, tests/cli/project/test_metadata.py, tests/cli/run/test_run.py, tests/cli/version/test_version.py
=> Improve compatibility checking for environments

docs/history/hatch.md, src/hatch/env/virtual.py
=> Properly allow overriding of `path`

.github/workflows/build-hatch.yml
Resolves https://github.com/pypa/hatch/issues/1170
=> Don't suppress errors for existing PyPI artifacts

docs/history/hatch.md, src/hatch/python/resolve.py, tests/cli/python/test_install.py, tests/conftest.py, tests/python/test_core.py, tests/python/test_resolve.py
=> Fix Python resolution of variants

tests/python/test_resolve.py
https://github.com/pypa/hatch/issues/1145#issuecomment-1868909505
=> Fix test that fails for openSUSE and other re-distributors

docs/blog/posts/release-hatch-190.md, docs/config/static-analysis.md, docs/history/hatch.md, src/hatch/cli/application.py, src/hatch/cli/fmt/__init__.py, src/hatch/cli/fmt/core.py, src/hatch/env/internal/static_analysis.py, tests/cli/fmt/test_fmt.py
Resolves https://github.com/pypa/hatch/discussions/1117
Resolves https://github.com/pypa/hatch/issues/1181
=> Make static analysis configurable

backend/src/hatchling/builders/wheel.py
Noticed PyCharm flagging this as I worked on #1195.
=> wheel: remove seemingly unnecessary local variable

docs/history/hatch.md, hatch.toml, src/hatch/template/files_default.py, tests/helpers/templates/new/default.py, tests/helpers/templates/new/feature_cli.py, tests/helpers/templates/new/feature_no_src_layout.py, tests/helpers/templates/new/licenses_empty.py, tests/helpers/templates/new/licenses_multiple.py, tests/helpers/templates/new/projects_urls_empty.py, tests/helpers/templates/new/projects_urls_space_in_label.py
Resolves https://github.com/pypa/hatch/issues/1262
=> Fix the `types` environment

.github/workflows/build-hatch.yml, docs/history/hatch.md, docs/install.md, pyoxidizer.bzl
Deprecation is not going to happen for a while https://discuss.python.org/t/consider-downgrading-windows-32-bit-from-tier-1-to-tier-2-or-tier-3-in-python-3-13/33719/49
=> Add back 32-bit builds for Windows

src/hatch/template/files_default.py, tests/cli/new/test_new.py, tests/cli/project/test_metadata.py, tests/helpers/templates/new/basic.py, tests/helpers/templates/new/default.py, tests/helpers/templates/new/feature_cli.py, tests/helpers/templates/new/feature_no_src_layout.py, tests/helpers/templates/new/licenses_empty.py, tests/helpers/templates/new/licenses_multiple.py, tests/helpers/templates/new/projects_urls_space_in_label.py
Since this {name} is obtained from git by default, it is most likely the user's GitHub username.
=> feat: Use user's name in project GitHub URL instead of "unknown"

backend/src/hatchling/builders/config.py, backend/src/hatchling/builders/hooks/plugin/interface.py, backend/src/hatchling/cli/build/__init__.py, docs/history/hatchling.md, docs/plugins/build-hook/reference.md, tests/backend/builders/test_custom.py
Resolves https://github.com/pypa/hatch/issues/1292
=> Add `dependencies` method to the build hook interface

backend/src/hatchling/builders/config.py, backend/src/hatchling/utils/fs.py, docs/history/hatchling.md, tests/backend/builders/test_config.py
Resolves https://github.com/pypa/hatch/issues/903
Resolves https://github.com/pypa/hatch/issues/1069
Resolves https://github.com/pypa/hatch/issues/1273
=> Respect VCS boundaries

backend/src/hatchling/builders/sdist.py, docs/history/hatchling.md
Resolves https://github.com/pypa/hatch/issues/1316
https://github.com/python/cpython/blob/516a6d4237fe3b9fb02a800b81a0a3153f78685e/Lib/tarfile.py#L2070-L2071
=> Ignore UNIX socket files

backend/src/hatchling/builders/constants.py, backend/src/hatchling/builders/plugin/interface.py, docs/history/hatchling.md, tests/backend/builders/plugin/test_interface.py
Resolves https://github.com/pypa/hatch/issues/1272
=> Ignore `.DS_Store` on macOS

backend/src/hatchling/metadata/core.py, docs/history/hatchling.md, tests/backend/metadata/test_core.py
Resolves https://github.com/pypa/hatch/issues/1325
Resolves https://github.com/pypa/hatch/issues/1326
=> Fix regression when loading metadata from source distributions

backend/src/hatchling/builders/config.py, docs/history/hatchling.md
=> Fix the `custom` build hook when using dynamic dependencies

backend/src/hatchling/metadata/core.py, docs/history/hatchling.md, tests/backend/metadata/test_core.py
=> Fix reading metadata from source distributions

docs/history/hatch.md, src/hatch/cli/application.py, src/hatch/cli/fmt/__init__.py, src/hatch/cli/shell/__init__.py, src/hatch/project/core.py, tests/project/test_core.py
Resolves https://github.com/pypa/hatch/issues/1166
=> Fix behavior of changing the current working directory

docs/history/hatch.md, src/hatch/cli/application.py, src/hatch/cli/fmt/core.py, src/hatch/cli/test/core.py, src/hatch/env/virtual.py, src/hatch/utils/fs.py, tests/cli/env/test_find.py
Resolves https://github.com/pypa/hatch/issues/1350
=> Maintain consistent data paths for case insensitive file systems

docs/.hooks/title_from_content.py
https://github.com/squidfunk/mkdocs-material/issues/7023#issuecomment-2041672128
=> Fix titles on social cards

backend/src/hatchling/dep/core.py, tests/backend/dep/test_core.py
https://github.com/astral-sh/uv/issues/3014
=> Handle UV bug

docs/history/hatch.md, src/hatch/__main__.py, src/hatch/cli/__init__.py
Resolves https://github.com/pypa/hatch/issues/1339
=> Fix the exit code when there happens to be an unhandled exception

docs/history/hatch.md, pyproject.toml, tests/python/test_core.py
Resolves https://github.com/pypa/hatch/issues/1395
=> Upgrade virtualenv dependency

docs/history/hatch.md, src/hatch/env/virtual.py, src/hatch/python/resolve.py, tests/python/test_resolve.py
Should fix 1482 but doesn't yet.  Will add a comment when it does.
=> Guess linux variant from cpuinfo

.github/workflows/build-distributions.yml
Seems pretty safe https://github.com/pypa/cibuildwheel/issues/331
=> Strip debug symbols

backend/src/hatchling/licenses/parse.py, backend/src/hatchling/version/source/code.py
RUF101 `PGH001` is a redirect to `S307`
=> Apply ruff rule RUF101

.github/workflows/build-distributions.yml, .github/workflows/build-hatch.yml, docs/history/hatch.md, release/unix/make_scripts_portable.py, release/windows/make_scripts_portable.py, ruff.toml
Resolves: https://github.com/pypa/hatch/issues/1498
It required https://github.com/astral-sh/uv/pull/3717
=> Fix entry points in the pre-built distribution that binaries use

docs/history/hatch.md, src/hatch/cli/env/run.py, src/hatch/cli/run/__init__.py, src/hatch/cli/test/__init__.py, src/hatch/utils/runner.py, tests/utils/test_runner.py
Resolves https://github.com/pypa/hatch/issues/1521
=> Treat inclusion variable options as an intersection

docs/history/hatch.md, src/hatch/utils/network.py
Resolves https://github.com/pypa/hatch/issues/1518
=> Add default timeout for network requests

tests/backend/builders/test_binary.py, tests/cli/publish/test_publish.py, tests/conftest.py
* Resolves https://github.com/pypa/hatch/issues/1509
* Resolves https://github.com/pypa/hatch/issues/1510
=> Improve markers for tests that should be skipped

docs/tutorials/python/manage.md, docs/why.md, mkdocs.yml, src/hatch/cli/python/find.py, src/hatch/cli/python/install.py, tests/cli/python/test_find.py, tests/cli/python/test_install.py
Resolves https://github.com/pypa/hatch/issues/1280
=> Add tutorial for managing Python distributions

docs/community/users.md
Add two Django projects that are now using hatch
=> Add Django-NYT and Django-Places to hatch users

docs/config/environment/advanced.md, docs/environment.md, docs/meta/faq.md
Resolves https://github.com/pypa/hatch/issues/1360
=> Remove Python 2 from documentation examples

docs/config/environment/overview.md
Please see https://github.com/pypa/hatch/discussions/1581 for the motivation to add some more information here.
=> docs: expand environment dev-mode description

backend/src/hatchling/metadata/core.py, backend/src/hatchling/metadata/spec.py, docs/history/hatchling.md, tests/backend/builders/test_wheel.py, tests/backend/metadata/test_core.py, tests/backend/metadata/test_spec.py
=> Update the default version of core metadata to 2.4

backend/src/hatchling/licenses/supported.py, docs/history/hatchling.md
Resolves https://github.com/pypa/hatch/issues/1797
Resolves https://github.com/pypa/hatch/issues/1806
=> Support an old import path

.github/workflows/test.yml, backend/pyproject.toml, backend/src/hatchling/builders/hooks/plugin/hooks.py, docs/history/hatch.md, docs/history/hatchling.md, pyproject.toml, src/hatch/cli/application.py, src/hatch/env/collectors/plugin/hooks.py, tests/cli/config/test_set.py, tests/cli/self/test_self.py
This addresses a couple of different issues that are open right now for failing tests. 
https://github.com/pypa/hatch/issues/2060 and https://github.com/pypa/hatch/issues/2056 
The fix for the self test that was failing for me locally was the only way I could get to work. I am not sure what the purpose of the env var was originally so that fix could be wrong.
=> Fix failing tests, handle subprocess buffering causing output issues on terminal
